print('-----------------------SEXTO DESAFIO-----------------------')
nome = input('Olá , qual seu nome?: ')
print('Muito bem vindo {} ^^'.format(nome))
n = int(input('Digite um número por gentileza:'))
d = (n*2)
t = (n*3)
r = (n**0.5)
print('Seguinte{},o número escolhido foi {}.\nO dobro de {} é {}\nO triplo de {} é {}\nE a raiz de {} é {}'.format(nome,n,n,d,n,t,n,r))
print('Obrigado por participar do programa {}'.format(nome))