a = input('Digite algo:')
print ('O tipo primitivo é ' ,type(a))
print ('É uma palavra?',a.isalpha())
print ('É um número?' ,a.isnumeric())
print ('Tem espaços?', a.isspace())
print ('Está todo em minúsculo?', a.islower())
print ('Está todo em maiúsculo?', a.isupper())
print ('Está com a primeira letra em maíusculo?', a.istitle())
print ('É uma palavra ou um número?', a.isalnum())