print('-----------------------QUINTO DESAFIO-----------------------')
nome = input('Olá , qual seu nome?:')
n1 = int(input('{},por favor escolha um número:'.format(nome)))
a = (n1-1)
s = (n1+1)
print('O sucessor de {} é {}.\nE o antecessor de {} é {}' .format(n1,s,n1,a))